Correções

diff --git a/data/in/SP/Santos/_pk020/makefile b/data/in/SP/Santos/_pk020/makefile
--- a/data/in/SP/Santos/_pk020/makefile
+++ b/data/in/SP/Santos/_pk020/makefile
@@ -1,38 +1,157 @@
+##
+## Template file reference: digital-preservation-BR/data/in/RS/PortoAlegre/_pk027
+## tplId: 027a
+##
+tplInputSchema_id=027a
 
+
+## BASIC CONFIG
 pg_io  =/tmp/pg_io
-ori    =/var/www/preserv.addressforall.org/download
-pg_base =ingest1
-pg_uri ="postgres://postgres@localhost/$(pg_base)"
+orig   =/var/www/preserv.addressforall.org/download
+pg_uri =postgres://postgres@localhost
+sandbox_root=/tmp/sandbox
+need_commands= 7z v16+; psql v12+; shp2pgsql v3+; 
+srid   =31983
 
-NRO_IMOVEL_ZIP     =$(ori)/b192fba419ef8133861a9051d2382d08476193eafbd8932f0ea05456157c301c.zip
-NRO_IMOVEL         =LOTES_PONTO_S2K
+pkid = 20
+fullPkID=20_001
+sandbox=$(sandbox_root)/_pk$(fullPkID)
 
+## USER CONFIGS
+pg_db  =ingest1
+thisTplFile_root = digital-preservation-BR
+
+## ## ## ## ## ## ##
+## THIS_MAKE, _pk20
+
+part1_file  =b192fba419ef8133861a9051d2382d08476193eafbd8932f0ea05456157c301c.zip
+part1_name  =Pontos de endereço
+
+## COMPOSED VARS
+pg_uri_db   =$(pg_uri)/$(pg_db)
+part1_path  =$(orig)/$(part1_file)
 
 all:
-	@echo Favor consultar as opcoes de target
+	@echo "=== Resumo deste makefile de recuperação de dados preservados ==="
+	@printf "Targets para a geração de layers:\n\tall_layers geoaddress \n"
+	@printf "Demais targets implementados:\n\tclean wget_files me\n"
+	@echo "A gereação de layers requer os seguintes comandos e versões:\n\t$(need_commands)"
 
-.SILENT: etl_toPgis_P2
+all_layers: geoaddress 
+	@echo "--ALL LAYERS--"
 
-etl_toPgis_P2:
-# ETL extrating to PostgreSQL/PostGIS the "P2" datatype (point and house number)
-	echo "Creating table ingest.pk020_p2 on PostGIS"
-	whoami
-	echo "Run with tmux and sudo! (DANGER: seems not idempotent on psql)"
-	mkdir -p $(pg_io)
-	psql $(pg_uri) -c "drop table if exists p2 cascade; drop table if exists ingest.pk020_p2 cascade;"
-	tput bold
-	echo Extraindo ....
-	tput sgr0
-	cd $(pg_io) ; 7z e -y  $(NRO_IMOVEL_ZIP) $(NRO_IMOVEL).* > /dev/null
-	echo "Conferindo se SRID esta configurado:"
-	( psql $(pg_uri) -c "SELECT srid, proj4text FROM spatial_ref_sys where srid=31983" )
-	echo Executando shp2pgsql ...
-	( cd $(pg_io) ; shp2pgsql -W iso-8859-1 -s 31983 $(NRO_IMOVEL).shp p2 | psql -q $(pg_uri) 2> /dev/null  )
-	echo "Conferira se bate o perfil:  43389 |  0.00 |  0.00 |  0.00 |     0.00 "
-	psql $(pg_uri) -c "SELECT count(*) n, round(max(a),2) a_max, round(min(a),2) a_min, round(avg(a),2) a_avg, round(percentile_disc(0.5) WITHIN GROUP ( ORDER BY a),2) a_median FROM ( select  st_area(geom) a from p2 ) t"
-	psql $(pg_uri) -c "CREATE TABLE ingest.pk020_p2 AS select gid, LOTE, L_NUMERO, X, Y, ST_centroid(ST_Transform(geom,4326)) as geom FROM p2"
-	echo Limpando...
-	rm $(pg_io)/$(NRO_IMOVEL).*
-	psql $(pg_uri) -c "drop table p2 cascade"
-	echo FIM.
+## ## ## ## ## ## ## ## ##
+## ## ## ## ## ## ## ## ##
+## Make targets of the Project Digital Preservation
+
+## ## ## ## sponsored by Project AddressForAll
+geoaddress: layername = geoaddress_full
+geoaddress: tabname = pk$(fullPkID)_p1_geoaddress
+geoaddress: makedirs $(part1_path)
+	@# pk20_p1 - ETL extrating to PostgreSQL/PostGIS the "geoaddress" datatype (point with house_number but no via name)
+	@echo
+	@echo "------------------------------------------"
+	@echo "------ Layer tipo $(layername)  ------"
+	@echo "-- Incluindo dados do arquivo-1 do package-$(fullPkID) na base $(pg_db) --"
+	@echo " Nome-hash do arquivo-1: $(part1_file)"
+	@echo " Tabela do layer geoaddress sem nome de rua, só com numero predial: $(tabname)"
+	@echo " Sub-arquivos do arquivo-1 com o conteúdo alvo: LOTES_PONTO_S2K.*"
+	@echo " Tema dos sub-arquivos: $(part1_name)"
+	@echo "Run with tmux and sudo! (DANGER: seems not idempotent on psql)"
+	@whoami
+	@printf "Above user is root? If not, you have permissions for all paths?\n [press ENTER for yes else ^C]"
+	@read _press_enter_
+	psql $(pg_uri_db) -c "DROP TABLE IF EXISTS $(tabname) CASCADE"
+	@tput bold
+	@echo Extracting ....
+	@tput sgr0
+	cd $(sandbox);  7z  x -y  $(part1_path) "LOTES_PONTO_S2K.*" ; chmod -R a+rx . > /dev/null
+	@echo "Conferindo se SRID 31983 esta configurado:"
+	@psql $(pg_uri_db) -c "SELECT srid, proj4text FROM spatial_ref_sys where srid=31983"
+	@echo "Tudo bem até aqui?  [ENTER para continuar ou ^C para rodar WS/ingest-step1]"
+	@read _tudo_bem_
+ifeq ('shp2sql','shp2sql')
+	@echo Executando shp2pgsql ...
+	cd $(sandbox);	shp2pgsql  -W latin1 -s 31983 "LOTES_PONTO_S2K.shp" $(tabname) | psql -q $(pg_uri_db) 2> /dev/null
+endif
+ifeq ('shp2sql','csv2sql')
+	@echo Executando csc2sql ...
+	psql $(pg_uri_db) -c "SELECT ingest.fdw_generate_direct_csv( '$(sandbox)/LOTES_PONTO_S2K.csv', '$(tabname)' )"
+endif
+	psql $(pg_uri_db) -c "SELECT ingest.any_load('shp2sql','$(sandbox)/LOTES_PONTO_S2K','$(layername)','$(tabname)','$(fullPkID)','$(part1_file)',array['gid', 'L_NUMERO AS pointer_number', 'X', 'Y', 'geom'])"
+	@echo "Confira os resultados nas tabelas ingest.layer_file e ingest.feature_asis".
+ifeq ('shp2sql','csv2sql')
+	psql $(pg_uri_db) -c "DROP FOREIGN TABLE IF EXISTS $(tabname)"
+endif
+	@echo FIM.
+
+geoaddress-clean: tabname = pk$(fullPkID)_p1_geoaddress
+geoaddress-clean:
+	rm -f "$(sandbox)/LOTES_PONTO_S2K.*" || true
+	psql $(pg_uri_db) -c "DROP TABLE IF EXISTS $(tabname) CASCADE"
+
+
+
+
+
+
+
+
+
+
+
+
+
+## ## ## ## ## ## ## ## ##
+## ## ## ## ## ## ## ## ##
+
+makedirs: clean_sandbox
+	@mkdir -p $(sandbox_root)
+	@mkdir -p $(sandbox)
+	@mkdir -p $(pg_io)
+
+wget_files:
+	@echo "Under construction, need to check that orig path is not /var/www! or use orig=x [ENTER if not else ^C]"
+	@echo $(orig)
+	@read _ENTER_OK_
+	mkdir -p $(orig)
+	@cd $(orig); wget http://dl.digital-guard.org/b192fba419ef8133861a9051d2382d08476193eafbd8932f0ea05456157c301c.zip
+	@echo "Please, if orig not default, run 'make _target_ orig=$(orig)'"
+
+
+## ## ## ##
+
+clean_sandbox:
+	@rm -rf $(sandbox) || true
+
+clean: geoaddress-clean nsvia-clean via-clean
+
+
+## ############################
+## SELF-GENERATE MAKE (make me)
+##
+
+thisTplFile  = digital-preservation-BR/src/maketemplates/make_ref027a.mustache.mk
+country      = BR
+baseSrc      = /opt/gits/_a4a
+
+srcPy        =  $(baseSrc)/digital-preservation/src/run_mustache.py
+mkme_input0  =  $(baseSrc)/digital-preservation-$(country)/src/maketemplates/commomFirst.yaml
+mkme_srcTplLast  =  $(baseSrc)/digital-preservation-$(country)/src/maketemplates/commomLast.mustache.mk
+mkme_srcTpl  =  $(baseSrc)/$(thisTplFile)
+mkme_input   = ./make_conf.yaml
+mkme_output  = /tmp/digitalPresservation-make_me.mk
+
+
+me: $(srcPy) $(mkme_input0) $(mkme_input) $(mkme_srcTpl)
+	@echo "-- Updating this make --"
+	python3 $(srcPy) -b $(baseSrc)/ -t $(mkme_srcTpl) --tplLast=$(mkme_srcTplLast) -i $(mkme_input) --input0=$(mkme_input0) > $(mkme_output)
+	@echo " Check diff, the '<' lines are the new ones... Something changed?"
+	@diff $(mkme_output) ./makefile || :
+	@echo "If some changes, and no error in the changes, move the script:"
+	@echo " mv ./makefile ./bk-makefile"
+	@echo " mv $(mkme_output) ./makefile"
+	@echo "[ENTER para rodar mv ou ^C para sair]"
+	@read _tudo_bem_
+	mv $(mkme_output) ./makefile
 
